name: bulk-scan-orchestrator
apiVersion: v2
home: https://github.com/hmcts/bulk-scan-orchestrator
version: 0.4.9
description: HMCTS Bulk scan orchestrator service
maintainers:
  - name: HMCTS BSP Team
    email: bspteam@hmcts.net
dependencies:
  - name: java
    version: 3.7.0
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
  - name: servicebus
    version: 0.3.1
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
    condition: servicebus.enabled
