name: bulk-scan-orchestrator
home: https://github.com/hmcts/bulk-scan-orchestrator
version: 0.1.1
description: HMCTS Bulk scan orchestrator service
maintainers:
  - name: HMCTS BSP Team
    email: bspteam@hmcts.net
