java:
  applicationPort: 8582
  readinessPath: '/health'
  livenessPath: '/health'
  secrets:
    SB_CONN_STRING:
      secretRef: servicebus-secret-namespace-${SERVICE_NAME}
      key: connectionString
  environment:
    ENVELOPES_QUEUE_CONNECTION_STRING: "$(SB_CONN_STRING);EntityPath=envelopes"
    PROCESSED_ENVELOPES_QUEUE_CONNECTION_STRING: "$(SB_CONN_STRING);EntityPath=processed-envelopes"
  keyVaults:
    "bulk-scan":
      resourceGroup: bulk-scan
      secrets:
        - idam-client-secret
        - idam-users-bulkscan-username
        - idam-users-bulkscan-password
    "s2s":
      resourceGroup: rpe-service-auth-provider
      secrets:
        - microservicekey-bulk-scan-orchestrator
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

servicebus:
  resourceGroup: bulk-scan-aks
  teamName: "Software Engineering"
  location: uksouth
  serviceplan: basic
  setup:
    queues:
      - name: envelopes
      - name: notifications
      - name: processed-envelopes

